// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPpFp_fRDqLuPniQ3jHEeBQdpnEtvKLKw',
    appId: '1:397486296081:android:3bab3a6772b8f8a4ea35b0',
    messagingSenderId: '397486296081',
    projectId: 'friday-app-4c871',
    databaseURL: 'https://friday-app-4c871-default-rtdb.firebaseio.com',
    storageBucket: 'friday-app-4c871.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTPSpG03wi7Bgw2OppKLw5ICTvFtNbv_8',
    appId: '1:397486296081:ios:6d1903ba5115a1caea35b0',
    messagingSenderId: '397486296081',
    projectId: 'friday-app-4c871',
    databaseURL: 'https://friday-app-4c871-default-rtdb.firebaseio.com',
    storageBucket: 'friday-app-4c871.appspot.com',
    androidClientId: '397486296081-drprh1439iqgdijebj07hi40kq1p3ueo.apps.googleusercontent.com',
    iosClientId: '397486296081-bs0irmpdah0m1tcikdjus7mrnvqqja20.apps.googleusercontent.com',
    iosBundleId: 'com.example.fridayApp',
  );
}
